settings:
  name: "How to enable StorageGRID in your environment"
  search: "storagegrid-enable,storagegrid-118,storagegrid-appliances"
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true


sidebar:
  entries:
    - title: How to enable StorageGRID
      url: /index.html
    - section: third-party
    - section: product-feature-guides
    - section: tools-apps-guides
    - section: examples
    - section: technical-reports
    - title: Blog posts
      url: /blogs.html
    - title: StorageGRID documentation
      url: /storagegrid-documentation.html
    - title: Legal notices
      url: /legal-notices.html
