---
permalink: tools-apps-guides/use-datadog-snmp.html
sidebar: sidebar
keywords: datadog, snmp
summary: Configure Datadog HQ to collect StorageGRID snmp metrics and traps. 
---
= Datadog HQ SNMP configuration.

:icons: font
:imagesdir: ../media/

[.lead]
Configure Datadog HQ to collect StorageGRID snmp metrics and traps.

== Datadog

=== Profile and Trap files Generated from StorageGRID MIB file
StorageGRID yaml file for Datadog Trap resolution mapping file. place in /etc/datadog-agent/conf.d/snmp.d/traps_db/ +
* link:../media/datadog/NETAPP-STORAGEGRID-MIB.yml[Download the trap yaml file] +
   *md5 checksum* 42e27e4210719945a46172b98c379517 +
   *sha256 checksum* d0fe5c8e6ca3c902d054f854b70a85f928cba8b7c76391d356f05d2cf73b6887 +

StorageGRID profile yaml file for Datadog metrics mapping. place in /etc/datadog-agent/conf.d/snmp.d/profiles/ +
* link:../media/datadog/netapp-storagegrid.yaml[Download the trap yaml file] +
   *md5 checksum* 72bb7784f4801adda4e0c3ea77df19aa +
   *sha256 checksum* b6b7fadd33063422a8bb8e39b3ead8ab38349ee0229926eadc8585f0087b8cee +  



SNMP configuration located in /etc/datadog-agent/datadog.yaml
 
=== SNMP configuration for Metrics

[source,yaml]
----
listeners:
  - name: snmp
snmp_listener:
  workers: 100  # number of workers used to discover devices concurrently
  discovery_interval: 3600  # interval between each autodiscovery in seconds
  loader: core  # use core check implementation of SNMP integration. recommended
  use_device_id_as_hostname: true  # recommended
  configs:
    - network_address: 10.0.0.0/24  # CIDR subnet
      snmp_version: 2
      port: 161
      community_string: 'st0r@gegrid'  # enclose with single quote
      profile: netapp-storagegrid
----


=== SNMP configuration for traps
 
[source,yaml]
---- 
network_devices:
  namespace:  # optional, defaults to “default”.
  snmp_traps:
    enabled: true
    port: 9162 # on which ports to listen for traps
    community_strings: # which community strings to allow for v2 traps
      - st0r@gegrid
----



/etc/datadog-agent/conf.d/snmp/d/conf.yaml
[source,yaml]
----  
init_config:
  loader: core  # use core check implementation of SNMP integration. recommended
  use_device_id_as_hostname: true  # recommended
instances:
- ip_address: '10.0.0.1'
  profile: netapp-storagegrid
  community_string: 'st0r@gegrid'  # enclose with single quote
- ip_address: '10.0.0.2'
  profile: netapp-storagegrid
  community_string: 'st0r@gegrid'
- ip_address: '10.0.0.3'
  profile: netapp-storagegrid
 community_string: 'st0r@gegrid'
- ip_address: '10.0.0.4'
  profile: netapp-storagegrid
  community_string: 'st0r@gegrid'
----

