---
permalink: monitor/alerts-monitoring.html
sidebar: sidebar
keywords: alerts, storagegrid
summary: Learn how to use the alerts system in StorageGRID for monitoring issues, managing custom alerts, and extending alert notifications via SNMP or email.

---
= Use alerts to monitor StorageGRID
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Learn how to use the alerts system in StorageGRID to monitor issues, manage custom alerts, and extend alert notifications using SNMP or email.

Alerts provide critical information that allow you to monitor the various events and conditions within your StorageGRID system.

The alerts system is designed to be the primary tool for monitoring any issues that might occur in your StorageGRID system. The alerts system focuses on actionable problems in the system and provides an easy-to-use interface.

We provide a variety of default alerting rules that aim to help monitor and troubleshoot your system. You can further manage alerts by creating custom alerts, editing or disabling default alerts, and silencing alert notifications.

Alerts are also extensible through SNMP or email notification.

For more information on alerts, see the https://docs.netapp.com/us-en/storagegrid-118/monitor/managing-alerts-and-alarms.html[product documentation^] available online and in PDF format.