---
permalink: monitor/index.html
sidebar: sidebar
keywords: monitoring, storagegrid
summary: Dive into understanding NetApp StorageGRID, its error conditions, and how to monitor it effectively using external applications like Splunk.

---
= Introduction to StorageGRID monitoring
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Learn how to monitor your StorageGRID system by using external applications, such as Splunk.

Effective monitoring of NetApp StorageGRID object-based storage enables administrators to quickly respond to urgent issues and to proactively add resources to handle growing workloads. This report provides general guidance about how to monitor key metrics and how to leverage external monitoring applications. It is meant to supplement the existing Monitoring and Troubleshooting guide. 

A NetApp StorageGRID deployment typically consists of multiple sites and many nodes that operate to create a distributed and fault-tolerant object storage system. In a distributed and resilient storage system such as StorageGRID, it is normal for error conditions to exist while the grid continues to operate normally. The challenge for you as an administrator is to understand the threshold at which error conditions (such as nodes down) present a problem that should be immediately addressed versus information that should be analyzed. By analyzing the data that StorageGRID presents, you can understand your workload and make informed decisions, such as when to add more resources.

StorageGRID provides excellent documentation that dives deep into the subject of monitoring. This report assumes that you are familiar with StorageGRID and that you have reviewed the documentation about it. Rather than repeating that information, we refer to the product documentation throughout this guide. StorageGRID product documentation is available online and in PDF format.

The goal of this document is to complement the product documentation and discuss how to monitor your StorageGRID system by using external applications, such as Splunk.

== Data sources
To successfully monitor NetApp StorageGRID, it is important to know where to gather data about the health and operations of your StorageGRID system.

* *Web UI and Dashboard.* The StorageGRID Grid Manager presents a top-level view of the information that you as an administrator need to see in a logical presentation. As an administrator, you can also dig deeper into service-level information for troubleshooting and log collections.
* *Audit Logs.* StorageGRID keeps granular audit logs of tenant actions such as PUT, GET, and DELETE. You can also trace the lifecycle of an object from ingest to the application of data management rules.
* *Metrics API.* Underlying the StorageGRID GMI are open APIs, as the UI is API-driven. This approach enables you to extract data by using external monitoring and analysis tools.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* NetApp StorageGRID Documentation Center
https://docs.netapp.com/us-en/storagegrid-118/
* NetApp StorageGRID Enablement
https://docs.netapp.com/us-en/storagegrid-enable/
* StorageGRID Documentation Resources page 
https://www.netapp.com/data-storage/storagegrid/documentation/
* NetApp Product Documentation 
https://www.netapp.com/support-and-training/documentation/ 
* NetApp StorageGRID App for Splunk
https://splunkbase.splunk.com/app/3898/#/details