---
sidebar: sidebar
permalink: commvault/solution-overview.html
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM
summary: Explore few use cases for StorageGRID configurations implemented by customers and NetApp IT.
---

= Tested solution overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The tested solution combines Commvault and NetApp solutions to make a powerful joint solution.

Commvault Complete Backup and Recovery software is an enterprise-level, integrated data and information management solution, built from the ground up on a single platform and with a unified code base. All of its functions share back-end technologies, bringing the unparalleled advantages and benefits of a fully integrated approach to protecting, managing, and accessing your data. The software contains modules to protect, archive, analyze, replicate, and search your data. The modules share a common set of back-end services and advanced capabilities that seamlessly interact with each other. The solution addresses all aspects of data management in your enterprise, while providing infinite scalability and unprecedented control of data and information.

Key features of the Commvault software platform include:

* A complete data protection solution supporting all major operating systems, applications, and databases on virtual and physical servers, NAS systems, cloud-based infrastructures, and mobile devices.
* Simplified management through a single console: You can view, manage, and access all functions and all data and information across the enterprise.
* Multiple protection methods including data backup and archiving, snapshot management, data replication, and content indexing for e-discovery.
* Efficient storage management using deduplication for disk and cloud storage.
* Integration with NetApp storage arrays such as AFF, FAS, NetApp HCI, and E-Series arrays and NetApp SolidFire^®^ scale-out storage systems. Integration also with NetApp Cloud Volumes ONTAP software to automate the creation of indexed, application-aware NetApp Snapshot™ copies across the NetApp storage portfolio.
* Complete virtual infrastructure management that supports leading on-premises virtual hypervisors and public cloud hyperscaler platforms.
* Advanced security capabilities to limit access to critical data, provide granular management capabilities, and provide single-sign-on access for Active Directory users.
* Policy-based data management that allows you to manage your data based on business needs—not physical location.
* A cutting-edge end-user experience, empowering your users to protect, find, and recover their own data.
* API-driven automation, allowing you to use third-party tools like vRealize Automation or Service Now to manage your data protection and recovery operations.

For details on supported workloads, visit https://www.commvault.com/supported-technologies[CommVault's supported technologies].

NetApp StorageGRID as a Commvault cloud tier is an enterprise hybrid-cloud object-storage solution. You can deploy it across many sites, either on a purpose-built appliance or as a software-defined deployment. StorageGRID enables you to establish data management policies that determine how data is stored and protected. StorageGRID collects the information you need to develop and enforce policies. It examines a wide range of characteristics and needs, including performance, durability, availability, geographic location, longevity, and cost. Data is fully maintained and protected as it moves between locations and as it ages.

The StorageGRID intelligent policy engine helps you choose either of the following options:

* To use erasure coding to back up data across multiple sites for resilience.
* To copy objects to remote sites to minimize WAN latency and cost.

When StorageGRID stores an object, you access it as one object, regardless of where it is or how many copies exist. This behavior is crucial for disaster recovery, because with it, even if one backup copy of your data is corrupted, StorageGRID is able to restore your data.

Retaining backup data in your primary storage can be expensive. When you use NetApp StorageGRID, you free up space on your primary storage by migrating inactive backup data into StorageGRID while you benefit from the numerous capabilities of StorageGRID. The value of backup data changes over time, as does the cost of storing it. StorageGRID can minimize the cost of your primary storage while increasing the durability of your data.

== Solution Setup 

In the lab setup, the StorageGRID environment consisted of four NetApp StorageGRID SG5712 appliances, one virtual primary Admin node and one virtual Gateway node. The SG5712 appliance is the entry level option—a baseline configuration. Choosing higher performance appliance options such as the NetApp StorageGRID SG5760 or SG6060 can provide significant performance benefits. Consult your NetApp StorageGRID solution architect for sizing assistance.

For its data protection policy, StorageGRID uses an integrated lifecycle management (ILM) policy to manage and protect data. ILM rules are evaluated in a policy from top to bottom. We implemented the ILM policy shown in the following table:

[cols="1a,1a,1a",options="header",]
|===
|ILM Rule |Qualifiers |Ingest Behavior
|Erasure Coding 2+1 |Objects over 200KB |Balanced
|2 Copy |All objects |Dual Commit
|===

The ILM 2 Copy rule is the default rule. The Erasure Coding 2+1 rule was applied for this testing to any object 200KB or larger. The default rule was applied to objects smaller than 200KB. Application of the rules in this way is a StorageGRID best practice.

For technical details about this test environment, read the Solution Design and Best Practices section in the https://www.netapp.com/us/media/tr-4831.pdf[NetApp Scale-out Data Protection with Commvault] technical report.

== StorageGRID Hardware Specifications 

The following table describes the NetApp StorageGRID hardware used in this testing. The StorageGRID SG5712 appliance with 10Gbps networking is the entry-level option and represents a baseline configuration. Optionally the SG5712 can be configured for 25Gbps networking.

[cols="1a,1a,1a,1a,1a",options="header",]
|===
|Hardware |Quantity |Disk |Usable Capacity |Network
|StorageGRID SG5712 appliances |4 |48 x 4TB (near-line SAS HDD) |136TB |10Gbps
|===

Choosing higher-performance appliance options such as the NetApp StorageGRID SG5760, SG6060, or all flash SGF6112 appliances can provide significant performance benefits. Consult your NetApp StorageGRID solution architect for sizing assistance.

== Commvault and StorageGRID Software Requirements

The following tables list the software requirements for the Commvault and NetApp StorageGRID software installed on VMware software for our testing. Four MediaAgent data transmission managers and one CommServe server were installed. In the test, 10Gbps networking was implemented for the VMware infrastructure. The following table 

The following table lists Commvault software total system requirements:

[cols="1a,1a,1a,1a,1a,1a",options="header",]
|===
|Component |Quantity |Datastore |Size |Total |Total Required IOPS
|CommServe Server |1 |OS |500GB |500GB |n/a
| | |SQL |500GB |500GB |n/a
|MediaAgent |4 |Virtual CPU (vCPU) |16 |64 |n/a
| | |RAM |128GB |512 |n/a
| | |OS |500GB |2TB |n/a
| | |Index Cache |2TB |8TB |200+
| | |DDB |2TB |8TB |200-80,000K
|===

In the test environment, one virtual primary Admin node and one virtual Gateway node were deployed on VMware on a NetApp E-Series E2812 storage array. Each node was on a separate server with the minimum production environment requirements described in the following table:

The following table list requirements for StorageGRID virtual Admin nodes and Gateway nodes:

[cols="1a,1a,1a,1a,1a",options="header",]
|===
|Node type |Quantity |vCPU |RAM |Storage
|Gateway node |1 |8 |24GB |100GB LUN for the OS
|Admin node |1 |8 |24GB a|
100GB LUN for the OS

200GB LUN for Admin node tables

200GB LUN for the Admin node audit log

|===
